Icon font selector
t3kit/theme_t3kit pull request #148
Opened 2017-04-06 13:09 UTC by pixelmatseriks

copied userFunc IconFontSelector to theme_t3kit, replaced usage of t3kit_extension_tools IconFontSelector to theme_t3kit IconFontSelector.

2017-04-07 11:40 UTC, MattiasNilsson requested changes
It looks good but I am not sure about the felayout_path?

2017-04-07 11:40 UTC, MattiasNilsson commented on Configuration/FlexForms/flexform_bigIconTextButton.xml
> +                                <cssFile>EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css</cssFile>
I am not sure we should use the felayout_t3kit path at all?

2017-04-07 11:40 UTC, MattiasNilsson commented on Configuration/FlexForms/flexform_div.xml
> +								<cssFile>EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css</cssFile>
I am not sure we should use the felayout_t3kit path at all?

2017-04-07 11:40 UTC, MattiasNilsson commented on Configuration/FlexForms/flexform_iconTextButton.xml
> +                                <cssFile>EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css</cssFile>
I am not sure we should use the felayout_t3kit path at all?

2017-04-07 11:40 UTC, MattiasNilsson commented on Configuration/TCA/Overrides/pages.php
> +        'cssFile' => 'EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css',
I am not sure we should use the felayout_t3kit path at all?

2017-04-10 06:19 UTC, dmh commented on Configuration/FlexForms/flexform_bigIconTextButton.xml
> +                                <cssFile>EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css</cssFile>
Even if we are not using `felayout_t3kit` as a separate repo I would like to keep it as a name of the folder inside of `theme_t3kit`. Just to let everyone know that it is `felayout` as it was in previous versions, and all FE stuff is here.

2017-04-10 06:19 UTC, dmh commented on Configuration/FlexForms/flexform_div.xml
> +								<cssFile>EXT:theme_t3kit/Resources/Public/felayout_t3kit/dev/fonts/style.css</cssFile>
Even if we are not using felayout_t3kit as a separate repo I would like to keep it as a name of the folder inside of theme_t3kit. Just to let everyone know that it is felayout as it was in previous versions, and all FE stuff is here.

2017-04-10 06:20 UTC, dmh approved these changes

2017-04-10 12:24 UTC, dmh commented
we will change felayout_t3kit path later after changing FE configurations

2017-04-10 12:25 UTC, merged