[TASK] add svg viewhelper to theme_t3kit and register t3kit fluid nam…
t3kit/theme_t3kit pull request #150
Opened 2017-04-07 10:56 UTC by pixelmatseriks

…espaces

2017-04-07 11:44 UTC, MattiasNilsson requested changes
This looks good just some smaller PHPCGL issues.

2017-04-07 11:44 UTC, MattiasNilsson commented on Classes/ViewHelpers/Render/SvgViewHelper.php
> +     * @param string $source
Add comment for method

2017-04-07 11:44 UTC, MattiasNilsson commented on Classes/ViewHelpers/Render/SvgViewHelper.php
> +            return 'no SVG file on /'.$source;
Add space between string concatenation.

2017-04-07 11:44 UTC, MattiasNilsson commented on Classes/ViewHelpers/Render/SvgViewHelper.php
> +        /*
Remove unused code.

2017-04-07 11:44 UTC, MattiasNilsson commented on Classes/ViewHelpers/Render/SvgViewHelper.php
> +    public function initializeArguments()
Add PHPdoc

2017-04-10 06:14 UTC, dmh approved these changes

2017-04-10 12:21 UTC, dmh commented
@MattiasNilsson

2017-04-10 13:04 UTC, MattiasNilsson commented
Looks good 👍

2017-04-10 13:04 UTC, merged